In [1]:
import numpy as np

In [9]:
v1=np.array([[3],[2]])

In [10]:
b1=np.array([[1,0],[0,1]])

In [14]:
b2=np.array([[3,-3],[4,-5]])

In [15]:
M=np.linalg.inv(b2)
M

array([[ 1.66666667, -1.        ],
       [ 1.33333333, -1.        ]])

In [16]:
M@v1

array([[3.],
       [2.]])

In [5]:
v2=b1@v1
v2

array([[3],
       [2]])